import type { Metadata } from "next";
import Link from "next/link";
import { Masthead } from "../components/masthead";
import { Choreography } from "../components/choreography";
import { loadSampleDocs } from "@/lib/documents";
import { buildLocalAnswer, countChunks } from "@/lib/rag";
import "../pages.css";

export const metadata: Metadata = {
  title: "GTM OS — how it works",
  description:
    "Four steps from a folder of documents to an answer with the source lines behind it, shown with a real worked example.",
};

const steps = [
  {
    tag: "Step 01",
    title: "Load the documents",
    body: "Drop in Markdown or text files, or paste text straight into the panel. The tool opens empty, so nothing is assumed about what you work on.",
    detail: [
      ["Input", "Pricing notes, call notes, memos, competitor research"],
      ["Reads", "Headings, section titles, and the document control block"],
      ["Stays in", "Your browser. No upload, no account, no storage"],
    ],
  },
  {
    tag: "Step 02",
    title: "It splits them into passages",
    body: "Each document is cut at its headings. A passage keeps its file name, its section heading, and the line numbers it came from. Those line numbers are the whole trick behind step four.",
    detail: [
      ["Cut at", "Every heading below the title"],
      ["Keeps", "File, section, first line, last line"],
      ["Result", "10 to 22 passages per document"],
    ],
  },
  {
    tag: "Step 03",
    title: "Ask in plain English",
    body: "Ask the way you would ask a coworker. The tool scores every passage against your question, keeps the best six, and writes the answer from those. Each one it used gets a number.",
    detail: [
      ["Method", "BM25, so a long rambling passage cannot win on repetition"],
      ["Returns", "Six passages, ranked, numbered [1] to [6]"],
      ["Checks", "Figures that disagree, and wording that overpromises"],
    ],
  },
  {
    tag: "Step 04",
    title: "Check the receipt",
    body: "Click any number. The source document opens beside the answer with the exact lines marked in cobalt. If the answer bent the wording, you see it in about a second.",
    detail: [
      ["Click", "Any [1] chip, or any source at the bottom of an answer"],
      ["Opens", "The document, scrolled to the marked lines"],
      ["Export", "Copy or download the answer as Markdown, citations included"],
    ],
  },
];

const limits = [
  "It only knows what you load. Ask about something outside the documents and it says so instead of guessing.",
  "Markdown and text only for now. PDF and Word are not parsed yet.",
  "Nothing is saved. Close the tab and the workspace is gone, which is the point for a demo but not for daily use.",
  "It reads and reasons over your documents. It does not publish, send, or approve anything.",
];

export default function HowItWorksPage() {
  const docs = loadSampleDocs();
  const passages = countChunks(docs);

  // The worked example below is generated at build time by the real engine,
  // so this page cannot drift from what the tool actually answers.
  const example = buildLocalAnswer(docs, "Is our pricing consistent?");
  const cited = example.evidence[0];
  const citedDoc = docs.find((doc) => doc.id === cited?.docId);
  const citedLines = citedDoc
    ? citedDoc.content
        .split("\n")
        .slice(cited.lineStart, cited.lineEnd + 1)
        .filter((line) => line.trim())
    : [];

  return (
    <>
      <Choreography />
      <Masthead current="how" />

      <main className="shell">
        <section className="page-head">
          <p className="tag tag-cobalt">How it works</p>
          <h1 className="display">Four steps from a messy folder to a checkable answer.</h1>
          <p className="lede">
            The demo set is {docs.length} documents and {passages} passages. Everything below runs in the browser tab,
            with no key and no account. The worked example further down is generated by the same code the tool runs.
          </p>
        </section>

        <section className="stack-section">
          <div className="stack-head">
            <span className="tag" data-reveal>
              01 · The idea
            </span>
            <h2 className="h2" data-reveal>
              An answer you cannot check is just a rumour with better grammar.
            </h2>
          </div>
          <div className="stack-body">
            <p className="prose" data-reveal>
              Most AI tools give you a confident paragraph and no way to test it. That is fine for a first draft and bad
              for anything a customer will read. GTM OS is built the other way round. The retrieval step comes first,
              the answer is written from what it found, and every claim carries a number that opens the source.
            </p>
            <p className="prose" data-reveal>
              That changes what the tool is for. It is less a writing assistant and more a way to find out whether your
              documents agree with each other before a rep quotes one of them on a call.
            </p>
          </div>
        </section>

        <section className="stack-section">
          <div className="stack-head">
            <span className="tag" data-reveal>
              02 · The steps
            </span>
            <h2 className="h2" data-reveal>
              About a minute to the first answer.
            </h2>
          </div>

          <div className="stack-body">
            <ol className="walk">
              {steps.map((step, index) => (
                <li className="walk-step" key={step.tag} data-reveal>
                  <div className="walk-copy">
                    <span className="tag tag-cobalt">{step.tag}</span>
                    <h3 className="h3">{step.title}</h3>
                    <p>{step.body}</p>
                    <div className="walk-detail">
                      {step.detail.map(([label, value]) => (
                        <div key={label}>
                          <strong>{label}</strong>
                          <span>{value}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="walk-demo" aria-hidden="true">
                    {index === 0 ? (
                      <>
                        <div className="demo-row demo-row-active">
                          <span>Load demo data</span>
                          <span className="demo-note">1 click</span>
                        </div>
                        <div className="demo-row">
                          <span>Add your own files</span>
                          <span className="demo-note">md · txt</span>
                        </div>
                        <div className="demo-row">
                          <span>Paste text instead</span>
                          <span className="demo-note">any length</span>
                        </div>
                      </>
                    ) : null}

                    {index === 1
                      ? docs.slice(0, 3).map((doc, position) => (
                          <div className="demo-row" key={doc.id}>
                            <span>
                              SRC {String(position + 1).padStart(2, "0")} · {doc.title}
                            </span>
                            <span className="demo-note">{doc.content.split("\n").length} lines</span>
                          </div>
                        ))
                      : null}

                    {index === 2 ? (
                      <>
                        <div className="demo-row demo-row-active">
                          <span>Is our pricing consistent?</span>
                          <span className="demo-note">enter</span>
                        </div>
                        <div className="demo-row">
                          <span>Scoring {passages} passages</span>
                          <span className="demo-note">bm25</span>
                        </div>
                        <div className="demo-row">
                          <span>
                            Kept {example.passageCount} from {example.docCount} documents
                          </span>
                          <span className="demo-note">ranked</span>
                        </div>
                      </>
                    ) : null}

                    {index === 3 ? (
                      <div className="paper">
                        <div className="paper-head">
                          <span className="tag">SRC 06</span>
                          <span className="pip pip-review">Needs review</span>
                        </div>
                        <div className="paper-body">
                          <p>
                            The early packaging model includes a{" "}
                            <span className="mark-band" data-sweep>
                              $999/month Starter plan
                            </span>{" "}
                            for mid-market fintech teams.
                          </p>
                        </div>
                      </div>
                    ) : null}
                  </div>
                </li>
              ))}
            </ol>
          </div>
        </section>

        <section className="stack-section">
          <div className="stack-head">
            <span className="tag" data-reveal>
              03 · A worked example
            </span>
            <h2 className="h2" data-reveal>
              One question, start to finish.
            </h2>
          </div>

          <div className="stack-body">
            <div className="worked" data-reveal>
              <div className="worked-side">
                <div className="worked-ask">
                  <span className="tag">You asked</span>
                  <p>{example.query}</p>
                </div>

                <div className="worked-answer">
                  <span className="tag tag-cobalt">GTM OS</span>
                  <p>{example.summary}</p>
                  {example.watchOut ? (
                    <>
                      <span className="worked-label">Watch out</span>
                      <p>{example.watchOut}</p>
                    </>
                  ) : null}
                  <span className="worked-label">Do this next</span>
                  <p>{example.nextStep}</p>
                </div>

                <p className="prose" style={{ fontSize: "var(--fs-xs)" }}>
                  {example.confidence}. Built from {example.passageCount} passages across {example.docCount} documents,
                  with no model key configured.
                </p>
              </div>

              <div className="worked-side">
                <span className="worked-label">What citation 1 opens</span>
                {citedDoc ? (
                  <div className="paper">
                    <div className="paper-head">
                      <span className="tag">{citedDoc.filename}</span>
                      <span className="tag">{cited.heading}</span>
                    </div>
                    <div className="paper-body">
                      {citedLines.slice(0, 4).map((line, position) => (
                        <p key={position} style={{ marginBottom: "8px" }}>
                          <span className="mark-band" data-sweep>
                            {line.replace(/^[-*+]\s+/, "")}
                          </span>
                        </p>
                      ))}
                    </div>
                  </div>
                ) : null}
                <p className="prose" style={{ fontSize: "var(--fs-xs)" }}>
                  Lines {cited ? cited.lineStart + 1 : 0} to {cited ? cited.lineEnd + 1 : 0} of the file. The tool
                  scrolls here and marks them, so you are reading the source rather than a summary of it.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="stack-section">
          <div className="stack-head">
            <span className="tag" data-reveal>
              04 · Limits
            </span>
            <h2 className="h2" data-reveal>
              What it will not do.
            </h2>
          </div>
          <div className="stack-body">
            <ul className="plain-list" data-reveal>
              {limits.map((line) => (
                <li key={line}>
                  <span aria-hidden="true" />
                  {line}
                </li>
              ))}
            </ul>
          </div>
        </section>

        <div className="page-next">
          <Link className="btn btn-primary" href="/tool">
            Open the tool
          </Link>
          <Link className="btn" href="/tech">
            See what it is built on
          </Link>
        </div>
      </main>
    </>
  );
}
